function clone(value) {
  return JSON.parse(JSON.stringify(value));
}

export const seedDoctors = [
  {
    id: "dr-aisha-rahman",
    userId: "usr-doc-aisha",
    name: "Dr. Aisha Rahman",
    specialty: "Cardiology",
    clinic: "Heart Rhythm Unit",
    experience: "11 years",
    fee: 1400,
    location: "New Delhi Central",
    languages: ["English", "Hindi", "Urdu"],
    nextAvailable: "Sat, 28 Mar at 4:30 PM",
    intro:
      "Focuses on preventive cardiac care, blood pressure stabilization, and post-episode follow-up plans.",
    about:
      "Dr. Rahman leads structured recovery pathways for patients with ongoing cardiac monitoring needs.",
    focusAreas: ["ECG review", "Risk counselling", "Diet planning"],
    credentials: "MD, DM Cardiology",
    tone: "teal",
    avatarLabel: "AR",
    schedule: [
      { date: "2026-03-28", label: "Sat, 28 Mar", slots: ["09:30 AM", "11:00 AM", "04:30 PM"] },
      { date: "2026-03-30", label: "Mon, 30 Mar", slots: ["10:00 AM", "01:00 PM", "03:30 PM"] },
      { date: "2026-04-01", label: "Wed, 1 Apr", slots: ["09:00 AM", "12:00 PM", "02:30 PM"] },
    ],
  },
  {
    id: "dr-karan-sood",
    userId: "usr-doc-karan",
    name: "Dr. Karan Sood",
    specialty: "Neurology",
    clinic: "Neuro Insight Clinic",
    experience: "9 years",
    fee: 1600,
    location: "Kanpur Outreach Desk",
    languages: ["English", "Hindi", "Punjabi"],
    nextAvailable: "Sun, 29 Mar at 11:30 AM",
    intro:
      "Treats migraine, sleep concerns, and long-running nerve pain with a strong emphasis on symptom tracking.",
    about:
      "Dr. Sood uses visit notes and follow-up reviews to make complex neurological care easier to monitor.",
    focusAreas: ["Migraine pathway", "Sleep review", "Nerve screening"],
    credentials: "MD, DNB Neurology",
    tone: "coral",
    avatarLabel: "KS",
    schedule: [
      { date: "2026-03-29", label: "Sun, 29 Mar", slots: ["09:30 AM", "11:30 AM", "05:00 PM"] },
      { date: "2026-03-31", label: "Tue, 31 Mar", slots: ["10:15 AM", "12:45 PM", "03:15 PM"] },
      { date: "2026-04-02", label: "Thu, 2 Apr", slots: ["08:45 AM", "11:15 AM", "01:45 PM"] },
    ],
  },
  {
    id: "dr-meera-joseph",
    userId: "usr-doc-meera",
    name: "Dr. Meera Joseph",
    specialty: "Pediatrics",
    clinic: "YoungCare Pavilion",
    experience: "13 years",
    fee: 1150,
    location: "New Delhi South",
    languages: ["English", "Hindi", "Malayalam"],
    nextAvailable: "Sat, 28 Mar at 2:15 PM",
    intro:
      "Handles child wellness, vaccination planning, and parent guidance through friendly, easy-to-follow care plans.",
    about:
      "Dr. Joseph combines child wellness visits with clear home guidance so guardians always know the next step.",
    focusAreas: ["Vaccination", "Growth tracking", "Parent counselling"],
    credentials: "MD Pediatrics",
    tone: "gold",
    avatarLabel: "MJ",
    schedule: [
      { date: "2026-03-28", label: "Sat, 28 Mar", slots: ["10:30 AM", "02:15 PM", "04:00 PM"] },
      { date: "2026-03-30", label: "Mon, 30 Mar", slots: ["09:00 AM", "12:30 PM", "03:00 PM"] },
      { date: "2026-04-03", label: "Fri, 3 Apr", slots: ["11:00 AM", "01:30 PM", "05:30 PM"] },
    ],
  },
  {
    id: "dr-rohan-iyer",
    userId: "usr-doc-rohan",
    name: "Dr. Rohan Iyer",
    specialty: "Orthopedics",
    clinic: "Mobility and Rehab Studio",
    experience: "12 years",
    fee: 1700,
    location: "Noida Mobility Hub",
    languages: ["English", "Hindi", "Tamil"],
    nextAvailable: "Mon, 30 Mar at 1:15 PM",
    intro:
      "Supports sports recovery, fracture follow-up, and structured mobility restoration after injury.",
    about:
      "Dr. Iyer focuses on progress-based recovery plans with milestone notes after each consultation.",
    focusAreas: ["Rehab plans", "Joint pain", "Fracture review"],
    credentials: "MS Orthopedics",
    tone: "navy",
    avatarLabel: "RI",
    schedule: [
      { date: "2026-03-30", label: "Mon, 30 Mar", slots: ["09:15 AM", "01:15 PM", "04:45 PM"] },
      { date: "2026-04-01", label: "Wed, 1 Apr", slots: ["10:00 AM", "12:30 PM", "03:00 PM"] },
      { date: "2026-04-04", label: "Sat, 4 Apr", slots: ["09:00 AM", "11:00 AM", "02:00 PM"] },
    ],
  },
  {
    id: "dr-sana-qureshi",
    userId: "usr-doc-sana",
    name: "Dr. Sana Qureshi",
    specialty: "Dermatology",
    clinic: "Skin Renewal Desk",
    experience: "8 years",
    fee: 1350,
    location: "Gurugram Skin Wing",
    languages: ["English", "Hindi", "Urdu"],
    nextAvailable: "Mon, 30 Mar at 10:45 AM",
    intro:
      "Cares for acne, eczema, pigment disorders, and long-term treatment adherence through digital review plans.",
    about:
      "Dr. Qureshi combines routine skin care management with practical lifestyle and medication guidance.",
    focusAreas: ["Acne care", "Eczema review", "Pigmentation plans"],
    credentials: "MD Dermatology",
    tone: "coral",
    avatarLabel: "SQ",
    schedule: [
      { date: "2026-03-30", label: "Mon, 30 Mar", slots: ["09:15 AM", "10:45 AM", "01:30 PM"] },
      { date: "2026-04-01", label: "Wed, 1 Apr", slots: ["11:15 AM", "02:00 PM", "04:15 PM"] },
      { date: "2026-04-03", label: "Fri, 3 Apr", slots: ["09:30 AM", "12:30 PM", "03:45 PM"] },
    ],
  },
  {
    id: "dr-dev-malhotra",
    userId: "usr-doc-dev",
    name: "Dr. Dev Malhotra",
    specialty: "General Medicine",
    clinic: "Primary Care Command",
    experience: "10 years",
    fee: 950,
    location: "New Delhi North",
    languages: ["English", "Hindi"],
    nextAvailable: "Sat, 28 Mar at 8:45 AM",
    intro:
      "Handles fever workups, chronic disease monitoring, and cross-referrals when multi-specialty care is needed.",
    about:
      "Dr. Malhotra acts as the first clinical touchpoint for patients who need broad evaluation and guided referrals.",
    focusAreas: ["Fever workup", "Diabetes review", "Referral planning"],
    credentials: "MD Internal Medicine",
    tone: "teal",
    avatarLabel: "DM",
    schedule: [
      { date: "2026-03-28", label: "Sat, 28 Mar", slots: ["08:45 AM", "11:45 AM", "03:15 PM"] },
      { date: "2026-03-31", label: "Tue, 31 Mar", slots: ["09:15 AM", "12:15 PM", "04:30 PM"] },
      { date: "2026-04-02", label: "Thu, 2 Apr", slots: ["10:00 AM", "01:00 PM", "05:00 PM"] },
    ],
  },
  {
    id: "dr-priya-nair",
    userId: "usr-doc-priya",
    name: "Dr. Priya Nair",
    specialty: "Gynecology",
    clinic: "Women Care Studio",
    experience: "14 years",
    fee: 1500,
    location: "Noida Women Hub",
    languages: ["English", "Hindi", "Malayalam"],
    nextAvailable: "Tue, 31 Mar at 2:00 PM",
    intro:
      "Supports cycle irregularity, antenatal review, and PCOS care through structured follow-up and counselling.",
    about:
      "Dr. Nair is focused on long-term women’s health planning with sensitive documentation and follow-up pathways.",
    focusAreas: ["PCOS support", "Cycle review", "Antenatal care"],
    credentials: "MS Obstetrics and Gynecology",
    tone: "gold",
    avatarLabel: "PN",
    schedule: [
      { date: "2026-03-31", label: "Tue, 31 Mar", slots: ["10:30 AM", "02:00 PM", "05:15 PM"] },
      { date: "2026-04-02", label: "Thu, 2 Apr", slots: ["09:00 AM", "12:30 PM", "03:30 PM"] },
      { date: "2026-04-04", label: "Sat, 4 Apr", slots: ["10:15 AM", "01:45 PM", "04:00 PM"] },
    ],
  },
  {
    id: "dr-harsh-bedi",
    userId: "usr-doc-harsh",
    name: "Dr. Harsh Bedi",
    specialty: "Gastroenterology",
    clinic: "Digestive Health Bay",
    experience: "12 years",
    fee: 1650,
    location: "Delhi Central",
    languages: ["English", "Hindi", "Punjabi"],
    nextAvailable: "Wed, 1 Apr at 11:45 AM",
    intro:
      "Reviews reflux, gut inflammation, and digestive complaints with diet-supported recovery plans.",
    about:
      "Dr. Bedi works on symptom-led digestive care with clear food, medication, and follow-up instructions.",
    focusAreas: ["Acidity control", "IBS review", "Liver screening"],
    credentials: "DM Gastroenterology",
    tone: "navy",
    avatarLabel: "HB",
    schedule: [
      { date: "2026-04-01", label: "Wed, 1 Apr", slots: ["09:15 AM", "11:45 AM", "03:00 PM"] },
      { date: "2026-04-03", label: "Fri, 3 Apr", slots: ["10:30 AM", "01:15 PM", "04:30 PM"] },
      { date: "2026-04-05", label: "Sun, 5 Apr", slots: ["09:45 AM", "12:15 PM", "02:45 PM"] },
    ],
  },
  {
    id: "dr-farah-siddiqui",
    userId: "usr-doc-farah",
    name: "Dr. Farah Siddiqui",
    specialty: "Pulmonology",
    clinic: "Breathing Care Unit",
    experience: "11 years",
    fee: 1550,
    location: "Ghaziabad Chest Wing",
    languages: ["English", "Hindi", "Urdu"],
    nextAvailable: "Tue, 31 Mar at 9:15 AM",
    intro:
      "Treats asthma flare-ups, wheezing, and chronic cough using lung monitoring and trigger-control plans.",
    about:
      "Dr. Siddiqui helps patients manage respiratory conditions with preventive guidance and digital follow-up.",
    focusAreas: ["Asthma review", "Breathlessness", "Allergy triggers"],
    credentials: "MD Pulmonary Medicine",
    tone: "teal",
    avatarLabel: "FS",
    schedule: [
      { date: "2026-03-31", label: "Tue, 31 Mar", slots: ["09:15 AM", "11:15 AM", "02:15 PM"] },
      { date: "2026-04-02", label: "Thu, 2 Apr", slots: ["10:45 AM", "01:45 PM", "04:15 PM"] },
      { date: "2026-04-05", label: "Sun, 5 Apr", slots: ["08:30 AM", "12:00 PM", "03:00 PM"] },
    ],
  },
  {
    id: "dr-nandini-rao",
    userId: "usr-doc-nandini",
    name: "Dr. Nandini Rao",
    specialty: "Psychiatry",
    clinic: "Mind Ease Clinic",
    experience: "9 years",
    fee: 1450,
    location: "Bengaluru Virtual Desk",
    languages: ["English", "Hindi", "Kannada"],
    nextAvailable: "Thu, 2 Apr at 4:00 PM",
    intro:
      "Works with anxiety, burnout, and sleep-related distress through supportive medication and therapy coordination.",
    about:
      "Dr. Rao creates low-friction mental health follow-up plans for patients who need regular check-ins.",
    focusAreas: ["Anxiety support", "Sleep health", "Stress review"],
    credentials: "MD Psychiatry",
    tone: "coral",
    avatarLabel: "NR",
    schedule: [
      { date: "2026-04-02", label: "Thu, 2 Apr", slots: ["10:00 AM", "01:00 PM", "04:00 PM"] },
      { date: "2026-04-04", label: "Sat, 4 Apr", slots: ["09:30 AM", "12:30 PM", "03:30 PM"] },
      { date: "2026-04-06", label: "Mon, 6 Apr", slots: ["11:00 AM", "02:00 PM", "05:00 PM"] },
    ],
  },
  {
    id: "dr-vikram-khanna",
    userId: "usr-doc-vikram",
    name: "Dr. Vikram Khanna",
    specialty: "ENT",
    clinic: "Sinus and Voice Center",
    experience: "10 years",
    fee: 1250,
    location: "Delhi West",
    languages: ["English", "Hindi"],
    nextAvailable: "Fri, 3 Apr at 1:00 PM",
    intro:
      "Handles sinus blockage, recurrent throat issues, and hearing complaints with structured follow-up review.",
    about:
      "Dr. Khanna focuses on practical symptom relief and persistent ENT conditions that need repeat monitoring.",
    focusAreas: ["Sinus review", "Throat pain", "Hearing checks"],
    credentials: "MS ENT",
    tone: "gold",
    avatarLabel: "VK",
    schedule: [
      { date: "2026-04-03", label: "Fri, 3 Apr", slots: ["09:45 AM", "01:00 PM", "04:00 PM"] },
      { date: "2026-04-05", label: "Sun, 5 Apr", slots: ["10:30 AM", "12:30 PM", "03:30 PM"] },
      { date: "2026-04-07", label: "Tue, 7 Apr", slots: ["08:45 AM", "11:45 AM", "02:45 PM"] },
    ],
  },
  {
    id: "dr-isha-kapoor",
    userId: "usr-doc-isha",
    name: "Dr. Isha Kapoor",
    specialty: "Endocrinology",
    clinic: "Hormone Balance Lab",
    experience: "13 years",
    fee: 1750,
    location: "Mumbai Endocrine Center",
    languages: ["English", "Hindi", "Marathi"],
    nextAvailable: "Fri, 3 Apr at 10:00 AM",
    intro:
      "Treats thyroid disorders, metabolic issues, and long-term endocrine monitoring with detailed follow-up plans.",
    about:
      "Dr. Kapoor helps patients manage hormone-related symptoms through careful test review and medication tracking.",
    focusAreas: ["Thyroid review", "Metabolic care", "Hormone monitoring"],
    credentials: "DM Endocrinology",
    tone: "navy",
    avatarLabel: "IK",
    schedule: [
      { date: "2026-04-03", label: "Fri, 3 Apr", slots: ["10:00 AM", "12:00 PM", "03:00 PM"] },
      { date: "2026-04-05", label: "Sun, 5 Apr", slots: ["09:15 AM", "01:15 PM", "04:15 PM"] },
      { date: "2026-04-08", label: "Wed, 8 Apr", slots: ["11:30 AM", "02:30 PM", "05:30 PM"] },
    ],
  },
  {
    id: "dr-kabir-ali",
    userId: "usr-doc-kabir",
    name: "Dr. Kabir Ali",
    specialty: "Nephrology",
    clinic: "Renal Monitoring Desk",
    experience: "12 years",
    fee: 1800,
    location: "New Delhi Renal Tower",
    languages: ["English", "Hindi", "Urdu"],
    nextAvailable: "Sat, 4 Apr at 11:15 AM",
    intro:
      "Supports kidney function monitoring, swelling evaluation, and hypertension-linked renal complications.",
    about:
      "Dr. Ali works with high-risk patients who need regular lab review and careful medication adjustments.",
    focusAreas: ["Kidney screening", "Swelling review", "Renal hypertension"],
    credentials: "DM Nephrology",
    tone: "teal",
    avatarLabel: "KA",
    schedule: [
      { date: "2026-04-04", label: "Sat, 4 Apr", slots: ["09:15 AM", "11:15 AM", "02:15 PM"] },
      { date: "2026-04-06", label: "Mon, 6 Apr", slots: ["10:30 AM", "01:30 PM", "04:30 PM"] },
      { date: "2026-04-08", label: "Wed, 8 Apr", slots: ["08:30 AM", "12:30 PM", "03:30 PM"] },
    ],
  },
];

export const seedUsers = [
  {
    id: "usr-admin-ritika",
    role: "admin",
    name: "Ritika Sen",
    email: "admin@medizyra.demo",
    password: "Admin@123",
    phone: "9890001001",
  },
  {
    id: "usr-doc-aisha",
    role: "doctor",
    name: "Dr. Aisha Rahman",
    email: "aisha@medizyra.demo",
    password: "Doctor@123",
    phone: "9890002001",
    linkedDoctorId: "dr-aisha-rahman",
  },
  {
    id: "usr-doc-karan",
    role: "doctor",
    name: "Dr. Karan Sood",
    email: "karan@medizyra.demo",
    password: "Doctor@123",
    phone: "9890002002",
    linkedDoctorId: "dr-karan-sood",
  },
  {
    id: "usr-doc-meera",
    role: "doctor",
    name: "Dr. Meera Joseph",
    email: "meera@medizyra.demo",
    password: "Doctor@123",
    phone: "9890002003",
    linkedDoctorId: "dr-meera-joseph",
  },
  {
    id: "usr-doc-rohan",
    role: "doctor",
    name: "Dr. Rohan Iyer",
    email: "rohan@medizyra.demo",
    password: "Doctor@123",
    phone: "9890002004",
    linkedDoctorId: "dr-rohan-iyer",
  },
  {
    id: "usr-doc-sana",
    role: "doctor",
    name: "Dr. Sana Qureshi",
    email: "sana@medizyra.demo",
    password: "Doctor@123",
    phone: "9890002005",
    linkedDoctorId: "dr-sana-qureshi",
  },
  {
    id: "usr-doc-dev",
    role: "doctor",
    name: "Dr. Dev Malhotra",
    email: "dev@medizyra.demo",
    password: "Doctor@123",
    phone: "9890002006",
    linkedDoctorId: "dr-dev-malhotra",
  },
  {
    id: "usr-doc-priya",
    role: "doctor",
    name: "Dr. Priya Nair",
    email: "priya@medizyra.demo",
    password: "Doctor@123",
    phone: "9890002007",
    linkedDoctorId: "dr-priya-nair",
  },
  {
    id: "usr-doc-harsh",
    role: "doctor",
    name: "Dr. Harsh Bedi",
    email: "harsh@medizyra.demo",
    password: "Doctor@123",
    phone: "9890002008",
    linkedDoctorId: "dr-harsh-bedi",
  },
  {
    id: "usr-doc-farah",
    role: "doctor",
    name: "Dr. Farah Siddiqui",
    email: "farah@medizyra.demo",
    password: "Doctor@123",
    phone: "9890002009",
    linkedDoctorId: "dr-farah-siddiqui",
  },
  {
    id: "usr-doc-nandini",
    role: "doctor",
    name: "Dr. Nandini Rao",
    email: "nandini@medizyra.demo",
    password: "Doctor@123",
    phone: "9890002010",
    linkedDoctorId: "dr-nandini-rao",
  },
  {
    id: "usr-doc-vikram",
    role: "doctor",
    name: "Dr. Vikram Khanna",
    email: "vikram@medizyra.demo",
    password: "Doctor@123",
    phone: "9890002011",
    linkedDoctorId: "dr-vikram-khanna",
  },
  {
    id: "usr-doc-isha",
    role: "doctor",
    name: "Dr. Isha Kapoor",
    email: "isha@medizyra.demo",
    password: "Doctor@123",
    phone: "9890002012",
    linkedDoctorId: "dr-isha-kapoor",
  },
  {
    id: "usr-doc-kabir",
    role: "doctor",
    name: "Dr. Kabir Ali",
    email: "kabir@medizyra.demo",
    password: "Doctor@123",
    phone: "9890002013",
    linkedDoctorId: "dr-kabir-ali",
  },
  {
    id: "usr-patient-anika",
    role: "patient",
    name: "Anika Sharma",
    email: "patient@medizyra.demo",
    password: "Patient@123",
    phone: "9810010010",
  },
  {
    id: "usr-patient-rahul",
    role: "patient",
    name: "Rahul Verma",
    email: "rahul@medizyra.demo",
    password: "Patient@123",
    phone: "9810010020",
  },
  {
    id: "usr-patient-neha",
    role: "patient",
    name: "Neha Gupta",
    email: "neha@medizyra.demo",
    password: "Patient@123",
    phone: "9810010030",
  },
  {
    id: "usr-patient-imran",
    role: "patient",
    name: "Imran Sheikh",
    email: "imran@medizyra.demo",
    password: "Patient@123",
    phone: "9810010040",
  },
  {
    id: "usr-patient-pooja",
    role: "patient",
    name: "Pooja Nair",
    email: "pooja@medizyra.demo",
    password: "Patient@123",
    phone: "9810010050",
  },
  {
    id: "usr-patient-farhan",
    role: "patient",
    name: "Farhan Ali",
    email: "farhan@medizyra.demo",
    password: "Patient@123",
    phone: "9810010060",
  },
  {
    id: "usr-patient-kavya",
    role: "patient",
    name: "Kavya Menon",
    email: "kavya@medizyra.demo",
    password: "Patient@123",
    phone: "9810010070",
  },
];

export const seedAppointments = [
  {
    id: "apt-seed-001",
    patientId: "usr-patient-anika",
    patientName: "Anika Sharma",
    patientEmail: "patient@medizyra.demo",
    phone: "9810010010",
    doctorId: "dr-aisha-rahman",
    doctorName: "Dr. Aisha Rahman",
    specialty: "Cardiology",
    appointmentDate: "2026-03-30",
    appointmentSlot: "10:00 AM",
    consultationMode: "In-clinic",
    priority: "Priority",
    reason: "Recurring palpitations after exertion",
    symptoms: "Short bursts of dizziness and chest tightness during evening walks.",
    status: "Confirmed",
    adminSummary: "Vitals check required at arrival. ECG room kept on standby.",
    doctorSummary: "",
    prescription: [],
    followUpDate: "",
    bookedAt: "2026-03-26T10:00:00.000Z",
    updatedAt: "2026-03-26T10:30:00.000Z",
  },
  {
    id: "apt-seed-002",
    patientId: "usr-patient-rahul",
    patientName: "Rahul Verma",
    patientEmail: "rahul@medizyra.demo",
    phone: "9810010020",
    doctorId: "dr-karan-sood",
    doctorName: "Dr. Karan Sood",
    specialty: "Neurology",
    appointmentDate: "2026-03-31",
    appointmentSlot: "12:45 PM",
    consultationMode: "Tele-consult",
    priority: "Routine",
    reason: "Weekly migraine flare-up",
    symptoms: "Light sensitivity and poor sleep for the last five nights.",
    status: "Requested",
    adminSummary: "",
    doctorSummary: "",
    prescription: [],
    followUpDate: "",
    bookedAt: "2026-03-27T07:30:00.000Z",
    updatedAt: "2026-03-27T07:30:00.000Z",
  },
  {
    id: "apt-seed-003",
    patientId: "usr-patient-anika",
    patientName: "Anika Sharma",
    patientEmail: "patient@medizyra.demo",
    phone: "9810010010",
    doctorId: "dr-meera-joseph",
    doctorName: "Dr. Meera Joseph",
    specialty: "Pediatrics",
    appointmentDate: "2026-03-22",
    appointmentSlot: "11:30 AM",
    consultationMode: "In-clinic",
    priority: "Routine",
    reason: "Vaccination counselling for younger sibling",
    symptoms: "Wanted guidance on fever management after scheduled immunization.",
    status: "Completed",
    adminSummary: "Guardian requested printed after-care instructions.",
    doctorSummary:
      "Provided immunization schedule, hydration advice, and fever red-flag counselling.",
    prescription: ["Paracetamol syrup if fever crosses 100F", "Hydration reminder"],
    followUpDate: "2026-09-22",
    bookedAt: "2026-03-18T09:15:00.000Z",
    updatedAt: "2026-03-22T13:00:00.000Z",
  },
  {
    id: "apt-seed-004",
    patientId: "usr-patient-neha",
    patientName: "Neha Gupta",
    patientEmail: "neha@medizyra.demo",
    phone: "9810010030",
    doctorId: "dr-isha-kapoor",
    doctorName: "Dr. Isha Kapoor",
    specialty: "Endocrinology",
    appointmentDate: "2026-04-03",
    appointmentSlot: "10:00 AM",
    consultationMode: "In-clinic",
    priority: "Routine",
    reason: "Thyroid-related fatigue and weight gain",
    symptoms: "Low energy, dry skin, and unexplained weight increase over two months.",
    status: "Requested",
    adminSummary: "",
    doctorSummary: "",
    prescription: [],
    followUpDate: "",
    bookedAt: "2026-03-27T09:10:00.000Z",
    updatedAt: "2026-03-27T09:10:00.000Z",
  },
  {
    id: "apt-seed-005",
    patientId: "usr-patient-imran",
    patientName: "Imran Sheikh",
    patientEmail: "imran@medizyra.demo",
    phone: "9810010040",
    doctorId: "dr-farah-siddiqui",
    doctorName: "Dr. Farah Siddiqui",
    specialty: "Pulmonology",
    appointmentDate: "2026-03-31",
    appointmentSlot: "11:15 AM",
    consultationMode: "Tele-consult",
    priority: "Priority",
    reason: "Asthma symptoms worsening after stair climbing",
    symptoms: "Night wheezing twice this week and shortness of breath after mild exertion.",
    status: "Confirmed",
    adminSummary: "Asked patient to keep inhaler history and trigger list ready for review.",
    doctorSummary: "",
    prescription: [],
    followUpDate: "",
    bookedAt: "2026-03-26T14:25:00.000Z",
    updatedAt: "2026-03-27T08:45:00.000Z",
  },
  {
    id: "apt-seed-006",
    patientId: "usr-patient-pooja",
    patientName: "Pooja Nair",
    patientEmail: "pooja@medizyra.demo",
    phone: "9810010050",
    doctorId: "dr-harsh-bedi",
    doctorName: "Dr. Harsh Bedi",
    specialty: "Gastroenterology",
    appointmentDate: "2026-03-24",
    appointmentSlot: "09:15 AM",
    consultationMode: "In-clinic",
    priority: "Routine",
    reason: "Burning acidity and bloating after meals",
    symptoms: "Upper abdominal burning, sour belching, and fullness after spicy food.",
    status: "Completed",
    adminSummary: "Patient reports symptoms increase late at night.",
    doctorSummary:
      "Likely reflux flare. Advised early dinner, trigger-food tracking, and 10-day medication course.",
    prescription: ["Pantoprazole 40 mg", "Avoid late-night meals", "Hydration plan"],
    followUpDate: "2026-04-14",
    bookedAt: "2026-03-20T11:20:00.000Z",
    updatedAt: "2026-03-24T13:40:00.000Z",
  },
  {
    id: "apt-seed-007",
    patientId: "usr-patient-farhan",
    patientName: "Farhan Ali",
    patientEmail: "farhan@medizyra.demo",
    phone: "9810010060",
    doctorId: "dr-rohan-iyer",
    doctorName: "Dr. Rohan Iyer",
    specialty: "Orthopedics",
    appointmentDate: "2026-04-01",
    appointmentSlot: "12:30 PM",
    consultationMode: "In-clinic",
    priority: "Routine",
    reason: "Knee pain after badminton sessions",
    symptoms: "Right knee stiffness and pain while squatting after weekend sports.",
    status: "Requested",
    adminSummary: "",
    doctorSummary: "",
    prescription: [],
    followUpDate: "",
    bookedAt: "2026-03-27T10:05:00.000Z",
    updatedAt: "2026-03-27T10:05:00.000Z",
  },
  {
    id: "apt-seed-008",
    patientId: "usr-patient-kavya",
    patientName: "Kavya Menon",
    patientEmail: "kavya@medizyra.demo",
    phone: "9810010070",
    doctorId: "dr-nandini-rao",
    doctorName: "Dr. Nandini Rao",
    specialty: "Psychiatry",
    appointmentDate: "2026-04-02",
    appointmentSlot: "04:00 PM",
    consultationMode: "Tele-consult",
    priority: "Priority",
    reason: "Anxiety and fragmented sleep",
    symptoms: "Frequent racing thoughts, early waking, and trouble focusing at work.",
    status: "Confirmed",
    adminSummary: "Patient asked for evening slot due office schedule.",
    doctorSummary: "",
    prescription: [],
    followUpDate: "",
    bookedAt: "2026-03-26T17:30:00.000Z",
    updatedAt: "2026-03-27T09:20:00.000Z",
  },
  {
    id: "apt-seed-009",
    patientId: "usr-patient-rahul",
    patientName: "Rahul Verma",
    patientEmail: "rahul@medizyra.demo",
    phone: "9810010020",
    doctorId: "dr-vikram-khanna",
    doctorName: "Dr. Vikram Khanna",
    specialty: "ENT",
    appointmentDate: "2026-03-21",
    appointmentSlot: "01:00 PM",
    consultationMode: "In-clinic",
    priority: "Routine",
    reason: "Repeated sinus blockage and morning headache",
    symptoms: "Blocked nose, heavy forehead pressure, and sore throat on waking.",
    status: "Completed",
    adminSummary: "Patient has history of seasonal allergies.",
    doctorSummary:
      "Sinus inflammation likely allergy-linked. Suggested steam inhalation and allergy control measures.",
    prescription: ["Saline nasal spray", "Antihistamine at night"],
    followUpDate: "2026-04-11",
    bookedAt: "2026-03-18T08:40:00.000Z",
    updatedAt: "2026-03-21T14:05:00.000Z",
  },
  {
    id: "apt-seed-010",
    patientId: "usr-patient-neha",
    patientName: "Neha Gupta",
    patientEmail: "neha@medizyra.demo",
    phone: "9810010030",
    doctorId: "dr-priya-nair",
    doctorName: "Dr. Priya Nair",
    specialty: "Gynecology",
    appointmentDate: "2026-04-02",
    appointmentSlot: "12:30 PM",
    consultationMode: "In-clinic",
    priority: "Routine",
    reason: "Irregular cycles and acne flare-up",
    symptoms: "Delayed periods for two months along with facial acne and fatigue.",
    status: "Requested",
    adminSummary: "",
    doctorSummary: "",
    prescription: [],
    followUpDate: "",
    bookedAt: "2026-03-27T11:45:00.000Z",
    updatedAt: "2026-03-27T11:45:00.000Z",
  },
  {
    id: "apt-seed-011",
    patientId: "usr-patient-imran",
    patientName: "Imran Sheikh",
    patientEmail: "imran@medizyra.demo",
    phone: "9810010040",
    doctorId: "dr-dev-malhotra",
    doctorName: "Dr. Dev Malhotra",
    specialty: "General Medicine",
    appointmentDate: "2026-03-29",
    appointmentSlot: "11:45 AM",
    consultationMode: "In-clinic",
    priority: "Routine",
    reason: "Fever with body ache and sore throat",
    symptoms: "Two days of low-grade fever, body ache, and painful swallowing.",
    status: "Completed",
    adminSummary: "Requested same-day review if fever rises.",
    doctorSummary:
      "Likely viral fever. Advised rest, fluids, and temperature monitoring with return precautions.",
    prescription: ["Paracetamol 650 mg", "Oral fluids", "Salt-water gargle"],
    followUpDate: "2026-04-02",
    bookedAt: "2026-03-28T07:50:00.000Z",
    updatedAt: "2026-03-29T13:10:00.000Z",
  },
  {
    id: "apt-seed-012",
    patientId: "usr-patient-pooja",
    patientName: "Pooja Nair",
    patientEmail: "pooja@medizyra.demo",
    phone: "9810010050",
    doctorId: "dr-sana-qureshi",
    doctorName: "Dr. Sana Qureshi",
    specialty: "Dermatology",
    appointmentDate: "2026-04-01",
    appointmentSlot: "11:15 AM",
    consultationMode: "Tele-consult",
    priority: "Routine",
    reason: "Persistent eczema patches on forearms",
    symptoms: "Itchy dry patches worsening after soap exposure and heat.",
    status: "Confirmed",
    adminSummary: "Patient uploaded photos before visit for comparison.",
    doctorSummary: "",
    prescription: [],
    followUpDate: "",
    bookedAt: "2026-03-27T08:20:00.000Z",
    updatedAt: "2026-03-27T09:05:00.000Z",
  },
];

export function createSeedState() {
  return {
    appointments: clone(seedAppointments),
    contactMessages: [],
    doctors: clone(seedDoctors),
    users: clone(seedUsers),
  };
}
